version: '3.3'
services:
  baseos:
    build: ./baseos/
    image: docker.pkg.github.com/cwxlab/openstack/baseos:stein
    container_name: baseos
    hostname: baseos
  database:
    depends_on:
      - baseos
    build: ./database/
    image: docker.pkg.github.com/cwxlab/openstack/database:stein
    container_name: database
    hostname: database
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: /var/opt/hosting/docker/openstack/database/stein/var/lib/mysql/
        target: /var/lib/mysql/
      - type: bind
        source: /opt/hosting/docker/openstack/database/stein/etc/mysql/mariadb.cond.d/99-openstack.conf
        target: /etc/mysql/mariadb.cond.d/99-openstack.conf
        read_only: true
  keystone:
    depends_on:
      - baseos
    build: ./keystone/
    image: docker.pkg.github.com/cwxlab/openstack/keystone:stein
    container_name: keystone
    hostname: keystone
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /opt/hosting/openstack/stein/Docker/keystone/etc/keystone/keystone.conf
        target: /etc/keystone/keystone.conf
        read_only: true
      - type: bind
        source: /opt/hosting/openstack/stein/Docker/keystone/etc/keystone/fernet-keys/
        target: /etc/keystone/fernet-keys/
      - type: bind
        source: /opt/hosting/openstack/stein/Docker/keystone/etc/keystone/credential-keys/
        target: /etc/keystone/credential-keys/
